### ISSUE TITLE
Optimize matching of castItems to particDesc

### ISSUE THREAD

**Issue by cmil** [dracor-org/fredracor#15]
Find ways of improving the matching of `castItem`s to construct the `particDesc`. One instance that need to be fixed is the usage of "empty-string" in `tc2dracor.xq`:

https://github.com/dracor-org/fredracor/blob/989f68ef457fc975b95a0456767433e94fb7af38/tc2dracor.xq#L97

This is a follow up issue to #13.

**Comment by lucagiovannini7** [comment]
Related issue: failed matching in the transformation might also result in the character's `sex `attribute being defaulted to `UNKNOWN`.

Here an example from Dalibray's _Soliman_ (**fre000425**): 

* [Original XML](https://github.com/dracor-org/theatre-classique/blob/main/xml/DALIBRAY_SOLIMAN.xml) (sex: 1 = male)
`<castItem><role id="GENTILHOMME DE SOLIMAN" sex="1" type="H" statut='aristocrate' age='A' stat_amour='néant'>GENTILHOMME DE SOLIMAN</role>.</castItem>`

* [DraCor XML](https://github.com/dracor-org/fredracor/blob/main/tei/dalibray-soliman.xml)
`<person xml:id="un-gentilhomme" sex="UNKNOWN"><!--WARNING: no castItem found for reference in @who-->`
`  <persName>Un gentilhomme</persName>`
`</person>`

If it is not going to break the workflow, I can correct these mistakes in the plays I'm using.
