### ISSUE TITLE
unresolved pair characters with 'et' in many French plays

### ISSUE THREAD

**Issue by DanilSko** [dracor-org/fredracor#20]
FreDraCor networks seem to be plagued with glued-together characters like "Ugande et Alcif", "Corisande et Florestan". In some 17 century plays such characters easily make up 30-50% of the network nodes which basically renders the whole network false. See example network for Amadis  by Philippe Quinault attached.   
![amadins_quinault](https://user-images.githubusercontent.com/19728469/217217694-e3b6fd02-e4ac-4bf8-8e9a-d076493d753f.png)
@lucagiovannini7 is going to check some of the plays relevant to his PhD research BUT we need a more systematic solution for the whole corpus. Especially since this looks like an automatable thing (split by ' et '). 
Of course, there are also many harder cases such as 'first african', 'second african', and 'both africans' making 3 nodes instead of 2, which also affects network metrics... But even resolving all "A et B" would be a giant leap for FreDraCor

**Comment by lehkost** [comment]
Well spotted, @DanilSko! We could *probably* apply these changes when converting our **_correction branch_** for upstream "Théâtre Classique" at https://github.com/dracor-org/theatre-classique to DraCor format – what do you think, @cmil?

In the [cited play](https://github.com/dracor-org/theatre-classique/blob/main/xml/QUINAULT_AMADIS.xml) it looks like this:
```xml
<sp stage="decor/location" who="URGANDE ET ALQUIF">
  <speaker>URGANDE ET ALQUIF sous un riche pavillon.</speaker>
    <l id="1">…</l>
    [etc.]
</sp>
```
If we choose to *automatically* split the original speaker string in two at all occurrences of " ET ", we should make extra sure we're not overdoing it. There might be other reasons for " ET " in that string. If we have that under control, let's do it as proposed.

**Comment by lucagiovannini7** [comment]
In the meanwhile, if I need to correct some character-related errors in the plays I'm using, should I do it [here](https://github.com/dracor-org/fredracor/tree/main/tei)? The [TEIs in the correction branch of the Theatre Classique repo](https://github.com/dracor-org/theatre-classique/tree/dracor/xml) do not have any `particDesc` yet (I suppose it's generated later in the workflow). Or would my changes break such workflow?

**Comment by cmil** [comment]
@DanilSko, @lucagiovannini7, @lehkost The above pull request should now fix most of these issues. It's a combination of programmatic changes and and corrections to the sources like this one: https://github.com/dracor-org/theatre-classique/commit/5e249f636621746c85677370ab7984b90adc2ae7.
