### ISSUE TITLE
Add dates for two plays

### ISSUE THREAD

**Issue by lehkost** [dracor-org/fredracor#29]
There are two plays without date at the moment:

* [Le Rosier du Cinquième](https://staging.dracor.org/fre/bonin-spencer-rosiercinquieme)
  * According to the About section [here](https://gallica.bnf.fr/ark:/12148/bpt6k9633504d), this one was printed in 1888.
* [Michel Lando](https://staging.dracor.org/fre/bouchor-michel-lando)
  * Printed in 1892 according to the title page.

Could we put this addition into the workflow?

**Comment by cmil** [comment]
> Could we put this addition into the workflow?

I added the years to the sources: dracor-org/theatre-classique@f6cdf0e171b8bfe1e5863a194d50af04c436ab2c. Is that what you meant, @lehkost?

**Comment by lehkost** [comment]
I actually had "ids.xml" in mind. With my latest commits, I inserted these two dates into "ids.xml".

**Comment by cmil** [comment]
> I actually had "ids.xml" in mind. With my latest commits, I inserted these two dates into "ids.xml".

That's also possible and in case of [Le Rosier du Cinquième](https://staging.dracor.org/fre/bonin-spencer-rosiercinquieme) maybe the better solution as the year does not seem to be in the source.
